# run in debug mode?
debug: False

# Settings for sample numbers and negative controls
sample_number_settings:
  # specify the format for sample numbers used in the input runsheet as a regex
  sample_number_format: '([BDPT]|[1357]0)([0-9]{8}|[0-9]{6})' # TODO: what is the format for sample numbers - probably numbers?
  format_in_sheet: '(?P<sample_type>[BDPT]|[1357]0)(?P<sample_number>\d{6})'
  format_in_lis: '(?P<sample_type>[BDPT])(?P<sample_year>\d{2})(?P<sample_number>\d{6})'
  # optional conversion between sample numbers starting with numbers vs letters (allowed values: number, letter)
  # if your sample numbers don't need conversion, set _in and _out to be the same - TODO: extra logic on switching
  sample_numbers_in: number
  sample_numbers_out: letter
  # mapping between sample number/letter if needed
  number_to_letter: { "70": "P", "30": "B", "10": "D", "50": "T"}
  date_settings:  # TODO: do we need this separately?
    splice_in_date: False  # for now we're assuming the date is there
    length_without_date: 8 # length is based on sample_numbers_in format - TODO: how to handle all this in sample sheet creation
    splice_after: 2 # location (1-based) at which to add year
  negative_control: '' # TODO: do we have negative controls?
  # list of positive controls - TODO: do we have them?
  positive_control: {}


barcode_format: "RB[0-9]{2}" # format of barcodes in runsheet
barcode_prefix: "RB" # barcode prefix as letter (for transferring original fastqs by barcode)

paths:
  output_base_path: "/path/to/analysis_outputs"

databases:
  emu_db: /path/to/emu_db